### ISSUE TITLE
Feature Request: Pet Display

### ISSUE THREAD

**Issue by kjbro** [Crytilis/mids-reborn-hero-designer#12]
Something which was in early stages in Pines but which isn't yet featured in Mids Reborn, Pet Display.

Workflow: 
-Player is making Mastermind
-Player selects pet power
-Player is able to click into pet power in order to see stats and powers on Pet, affected by currently slotting.

Additional/Bonus functionality:
-Clear denotation of which powers in the pet's list have the potential to trigger slotted procs.  
-Ability to factor in buffs from other pets (Example: Thugs, where T2s have leadership auras which apply to other pets)
-Ability to factor in buffs from Mastermind (Example: Force Fields, where you can apply single-target bubbles to pets)
-Inclusion of non-MM pets?

Value proposition:
Mastermind players often care more about pet stats than personal stats.  The inability to see power statistics and totals for pets in Mids when building is crippling.

**Comment by Crytilis** [comment]
Added and improved in 2.6.0.4 :)
