### ISSUE TITLE
Missing Set Options for Pet Summons

### ISSUE THREAD

**Issue by Aethar** [Crytilis/mids-reborn-hero-designer#14]
Theese two Pet-Summoning powers for Mastermind are missing the following Set Enhancement categories (as per Homecoming servers).

Soldiers, missing IO Sets: Healing and Knockback.
Spec-Ops, missing IO Sets: Hold, Stun, Immobilize, and Accurate To-Hit Debuff.

Commandos looked alright.

**Comment by Crytilis** [comment]
@Aethar Thanks for the report, I will get these adding in the upcoming version.

**Comment by Crytilis** [comment]
Fixed
