### ISSUE TITLE
Powerset load failure

### ISSUE THREAD

**Issue by Voltixdark** [Crytilis/mids-reborn-hero-designer#15]
**Describe the bug**
Every time I open the mids program I get a Powerset load failure title box with the error in the details box "Failed to load powerset by name:Pool.Fitness at 6"
**To Reproduce**
1. Go to 'the desktop'
2. Click on 'double click the Mids Reborn exe icon'

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23109995/67620660-3d4d0d80-f7d7-11e9-85b0-c9de7c0ef6de.JPG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [70]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Crytilis** [comment]
fixed
