### ISSUE TITLE
Defense number seem off on several sets

### ISSUE THREAD

**Issue by whiteshadow01** [Crytilis/mids-reborn-hero-designer#23]
I have recently used Mids to build characters and the defense numbers in mids look amazing but when I build the character in the game the defense numbers in mids are off by approximately 6%.  I have found two sets so far that are reporting different in mids from the actual game.  Time Manipulation for Corrupters, Farsight seems a lot higher in Mids than the real game.  Scrapper the Energy Manipulation set seems to report higher values as well. It seems that there is discrepancies on all defense number for these sets even weave and combat jumping are reporting higher numbers.

**Comment by Crytilis** [comment]
Please upgrade
