### ISSUE TITLE
Resistance numbers seem off!!!!!

### ISSUE THREAD

**Issue by whiteshadow01** [Crytilis/mids-reborn-hero-designer#24]
I made a staff/elec brute
Built him out in mids.
http://www.cohplanner.com/mids/download.php?uc=1521&c=703&a=1406&f=HEX&dc=78DA6594594F13611486BFA1532AA5A554A05028BB50A0B4B480896B8C0A98281812126F9B06066852DB665A8C5CFA0F5CE38D0B08B85DF853DCA3FE03F5C2E54205A2493D9DF7A534E924ED33F39EE53BE77CDFCCCCD509D78B73D74E29ADF66C2A91CBC5CF982B79C37131915F3113299B52CA339932E6F366263D95C8E52357C61CA2B55A5EF11923651891B97C6271313E955C5ACE27D34B0198268C45239D3322084ECEC74F9B9733A672CE6632A9C85CD63016DCD6ED5E98CB7A9A36125979F0EC3D2C18666E3999F54F6693F391C9B4612EADC667A40CC35C45A12D524C487E2FBB15AF824D85AA948AE9CA35000EF783E120B85174D32C5FBBFA65B3B4FADFE0C13FE436D8B843364B40BBAE368BA18CD54E205FD549F208A81F258F81D5C7C15752A30DB155B626CDD25A1BC1C10B58674BAC76E6B78FC3561D050FC4C851D039461E065F4B7E07631D5BC857B709F6AE8187D6C947E406F846626B105B782CFFB59C65ED08ECAE18F34539AF51B0474E831BBECA5DDC88E25AA279A0699E36F885FDE01351BDB0D9BD9CBD8FB3F771F62D9C7D0B673FBC0B7E901A1BD85F8357B7B4AE7AB0DB45BAC93AB0D7033E95A826C4AAA630EAD4A4CE66D6DE5C904BD944F143D1FD9C7E2BA71FE0F4039CFE20A7AF4B4C1B326B6DDCD52077F5A354DCCE6EDBD75149C71A798FBCCF4E1E900FC16712D589BCB6CE6E4C60A88B0C901DE073F1EA514EAB869E1C4E5B6F1AFC2435F4B186BE3BC8DD7F9BBC4EDE008337C95BA04F7A1B606F03EC6D90BDD5C83686585F6807FEE16D706497FC07BAC43742DF08B591BF608C3131E6F0CA9A519E9E28D78C71CD805E7ACB8B0755766CA842895628B10A65AC4219AF50A6F4D257A2305D619DD5691445B3949A7A79BBA114BE394B5F095A7FEC2B9A7609DD0C9F170675F5BDC2FB67B97217FBF8D957AAA1F0A5ECFEAB6FBFCEB7C5B798FABBB2FBF765F7FF01CD7C01D4
When i built him in game his resistance numbers were way off from the 90% reported in mids.
I looked at charged armor and in mids it states with the slotting I have it should be 55.82%
In game however it is 41.86!!!!!!

**Expected behavior**
I would expect the numbers to match exactly 

**Screenshots**
![resistance numbers off](https://user-images.githubusercontent.com/31144980/84596452-b787dc00-ae12-11ea-81e9-b6c965dda47b.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 64
 - Chrome
 - Application Version 2.7.1.15
 - Database Version 20.0426

**Additional context**
I love love love your program and depend heavily on it for mybuilds but if the defense and resistance numbers are this far off from in game numbers, I cannot depend on it.

**Comment by Crytilis** [comment]
@whiteshadow01 Please update to the latest version 2.7.2.10
